[%
    T = {
        configure_1                                = "IntranetUserJS: Qslip keyboard shortcut Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Qslip keyboard shortcut &rsaquo; Configuration",
        configure_5                                = "Report ID to be used:",
        configure_6                                = "Save configuration",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Qslip keyboard shortcut",
        viewjs_2                                   = "&rsaquo; QslipKeyShortcut &rsaquo; View JS Tool",
    }
%]
