[%
    T = {
        configure_1                                = "IntranetUserJS: Päivän lainat -näppäinkomento",
        configure_2                                = "Etusivu",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: Päivän lainat -näppäinkomento &rsaquo; Asetukset",
        configure_5                                = "Käytettävän raportin ID:",
        configure_6                                = "Tallenna asetukset",
        configure_7                                = "Päivityksen tila",
        configure_8                                = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Qslip-pikanäppäin",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Qslip-pikanäppäin &rsaquo; Näytä JS-liitännäinen",
    }
%]