[%
    T = {
        configure_1                                = "IntranetUserJS: Dagens lån-kortkommando",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Dagens lån-kortkommando &rsaquo; Inställningar",
        configure_5                                = "ID för rapporten som ska användas:",
        configure_6                                = "Spara inställningar",
        configure_7                                = "Uppdateringsstatus",
        configure_8                                = "Plugin har aldrig uppdaterats.",
        viewjs_1                                   = "IntranetUserJS: Dagens lån-kortkommando",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Dagens lån-kortkommando &rsaquo; Visa JS-plugin",
    }
%]